// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package quizcarte.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	/**
	 * @deprecated
	 * The default constructor of the Microflows class should not be used.
	 * Use the static microflow invocation methods instead.
	 */
	@java.lang.Deprecated(since = "9.12", forRemoval = true)
	public Microflows() {}

	// These are the microflows for the QuizCarte module
	public static void aCT_split(IContext context, quizcarte.proxies.JsonObject _jsonObject, quizcarte.proxies.Test _test)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JsonObject", _jsonObject == null ? null : _jsonObject.getMendixObject());
		params.put("Test", _test == null ? null : _test.getMendixObject());
		Core.microflowCall("QuizCarte.ACT_split").withParams(params).execute(context);
	}
	public static void afficher_Resultat(IContext context, quizcarte.proxies.Test _test, quizcarte.proxies.Input _input)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Test", _test == null ? null : _test.getMendixObject());
		params.put("Input", _input == null ? null : _input.getMendixObject());
		Core.microflowCall("QuizCarte.Afficher_Resultat").withParams(params).execute(context);
	}
	public static void bad_AnswerB(IContext context, quizcarte.proxies.JsonObject _jsonObject, quizcarte.proxies.Test _test, quizcarte.proxies.Input _input)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JsonObject", _jsonObject == null ? null : _jsonObject.getMendixObject());
		params.put("Test", _test == null ? null : _test.getMendixObject());
		params.put("Input", _input == null ? null : _input.getMendixObject());
		Core.microflowCall("QuizCarte.Bad_AnswerB").withParams(params).execute(context);
	}
	public static void bad_AnswerC(IContext context, quizcarte.proxies.JsonObject _jsonObject, quizcarte.proxies.Test _test, quizcarte.proxies.Input _input)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JsonObject", _jsonObject == null ? null : _jsonObject.getMendixObject());
		params.put("Test", _test == null ? null : _test.getMendixObject());
		params.put("Input", _input == null ? null : _input.getMendixObject());
		Core.microflowCall("QuizCarte.Bad_AnswerC").withParams(params).execute(context);
	}
	public static void bad_AnswerD(IContext context, quizcarte.proxies.JsonObject _jsonObject, quizcarte.proxies.Test _test, quizcarte.proxies.Input _input)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JsonObject", _jsonObject == null ? null : _jsonObject.getMendixObject());
		params.put("Test", _test == null ? null : _test.getMendixObject());
		params.put("Input", _input == null ? null : _input.getMendixObject());
		Core.microflowCall("QuizCarte.Bad_AnswerD").withParams(params).execute(context);
	}
	public static quizcarte.proxies.Input creation_Input(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("QuizCarte.Creation_Input").withParams(params).execute(context);
		return result == null ? null : quizcarte.proxies.Input.initialize(context, result);
	}
	public static void good_Answer(IContext context, quizcarte.proxies.JsonObject _jsonObject, quizcarte.proxies.Test _test, quizcarte.proxies.Input _input)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JsonObject", _jsonObject == null ? null : _jsonObject.getMendixObject());
		params.put("Test", _test == null ? null : _test.getMendixObject());
		params.put("Input", _input == null ? null : _input.getMendixObject());
		Core.microflowCall("QuizCarte.Good_Answer").withParams(params).execute(context);
	}
	public static void question_Suivante(IContext context, quizcarte.proxies.Test _test, quizcarte.proxies.Input _input)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Test", _test == null ? null : _test.getMendixObject());
		params.put("Input", _input == null ? null : _input.getMendixObject());
		Core.microflowCall("QuizCarte.Question_Suivante").withParams(params).execute(context);
	}
	public static void show_Open_Carte(IContext context, quizcarte.proxies.JsonObject _jsonObject, quizcarte.proxies.Test _test, quizcarte.proxies.Input _input)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("JsonObject", _jsonObject == null ? null : _jsonObject.getMendixObject());
		params.put("Test", _test == null ? null : _test.getMendixObject());
		params.put("Input", _input == null ? null : _input.getMendixObject());
		Core.microflowCall("QuizCarte.Show_Open_Carte").withParams(params).execute(context);
	}
	public static quizcarte.proxies.JsonObject sUB_Rest(IContext context, quizcarte.proxies.Test _test, quizcarte.proxies.Input _input)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Test", _test == null ? null : _test.getMendixObject());
		params.put("Input", _input == null ? null : _input.getMendixObject());
		IMendixObject result = (IMendixObject)Core.microflowCall("QuizCarte.SUB_Rest").withParams(params).execute(context);
		return result == null ? null : quizcarte.proxies.JsonObject.initialize(context, result);
	}
}
